### PR TITLE
Update settings.py

### PR DESCRIPTION
**Pull request by thehappyhippo**

### CODE REVIEW

**Comment by troeger** [comment]
Looks good. Could you resolve the conflict first, by pulling the latest changes into your fork?

**Comment by thehappyhippo** [comment]
Tried already, not successful :(

**Comment by thehappyhippo** [comment]
So now its possible to merge. Many changes in the executor. Run this version on Windows (with small mods https://github.com/troeger/opensubmit/compare/master...thehappyhippo:master#diff-1390d49e922b620ca6e8b815340112a2R373,https://github.com/troeger/opensubmit/compare/master...thehappyhippo:master#diff-1390d49e922b620ca6e8b815340112a2R305) on Linux

**Comment by troeger** [comment]
Thanks for the work. I will do some additional tests on Linux and MacOSX with the merge result.

**Comment by troeger** [comment]
Does that close any issues, @thehappyhippo ?

**Comment by thehappyhippo** [comment]
https://github.com/troeger/opensubmit/issues/54 Most changes result from the Windows port, but showed limitations on other platforms also e.g. locking, error handling, processor info.

**Comment by troeger** [comment]
What about #76 and #85 ?

**Comment by thehappyhippo** [comment]
Not sure with if kill process works as expected #76, but multiple executors are
impossible. #85 will be catched but not resolved.

**Pull request merged**
